#!/bin/bash

if which docker-compose 2>/dev/null ;then
    COMPOSE=$(which docker-compose)
else
    COMPOSE="$(which docker) compose"
fi

## Populate env file
echo SQL_SERVER=db > ${PWD}/env
echo SQL_DATABASE=dyalog_cms >> ${PWD}/env
echo SQL_USER=dcms >> ${PWD}/env
echo SQL_PASSWORD=apl >> ${PWD}/env
echo SQL_PORT=3306 >> ${PWD}/env
echo MYSQL_SERVER=db >> ${PWD}/env
echo MYSQL_DATABASE=dyalog_cms >> ${PWD}/env
echo MYSQL_USER=dcms >> ${PWD}/env
echo MYSQL_PASSWORD=apl >> ${PWD}/env
echo MYSQL_PORT=3306 >> ${PWD}/env
echo SECRETS=/app/secrets/secrets.json5 >> ${PWD}/env
echo RIDE_INIT=HTTP:*:4502 >> ${PWD}/env
echo CONFIGFILE=/app/dev.dcfg >> ${PWD}/env
echo MYSQL_RANDOM_ROOT_PASSWORD=1 >> ${PWD}/env

echo COMPOSE IS: $COMPOSE
echo "Use docker inspect to get the IP of the running container"

$COMPOSE pull
$COMPOSE -f docker-compose.yml up
