services:
  db:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1073741824"
    env_file: env
    image: mariadb:10.8.2
    networks:
      dcms: null
    tty: true
    volumes:
      - /DockerVolumes/ftp/dcmsweb/master//dcms_db:/var/lib/mysql
        #      - /DockerVolumes/database-backups/r-DCMS-db-1/backup:/docker-entrypoint-initdb.d
  web:
    deploy:
      labels:
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.http.routers.dcms-http.entrypoints: http
        traefik.http.routers.dcms-http.middlewares: https-redirect
        traefik.http.routers.dcms-http.rule: Host(`dcms.gos.dyalog.com`,`dcms.dyalog.com`)
        traefik.http.routers.dcms-https.entrypoints: https
        traefik.http.routers.dcms-https.rule: Host(`dcms.gos.dyalog.com`,`dcms.dyalog.com`)
        traefik.http.routers.dcms-https.tls: "true"
        traefik.http.routers.dcms-https.tls.certresolver: le
        traefik.http.services.dcms.loadbalancer.server.port: "8080"
      resources:
        limits:
          cpus: "0.50"
          memory: "1073741824"
    env_file: env
    image: dyalog/techpreview:latest
    networks:
      dcms: null
      traefik-public: null
    tty: true
    volumes:
    - appvol:/app
    - appdatavol:/data
    - appsecretsvol:/secrets

networks:
  dcms:
    name: dcms_dcms
  traefik-public:
    name: traefik-public
    external: true

volumes:
  appdatavol:
    name: dcms_appdatavol
    driver: local
    driver_opts:
      device: :/DockerVolumes/ftp/dcmsweb/master/data
      o: addr=81.94.205.34,nolock,soft,rw
      type: nfs
  appsecretsvol:
    name: dcms_appsecretsvol
    driver: local
    driver_opts:
      device: :/DockerVolumes/ftp/dcmsweb/master/secrets
      o: addr=81.94.205.34,nolock,soft,rw
      type: nfs
  appvol:
    name: dcms_appvol
    driver: local
    driver_opts:
      device: :/DockerVolumes/ftp/dcmsweb/master
      o: addr=81.94.205.34,nolock,soft,rw
      type: nfs
